"""
=============================================================================
ABOUT MEMOLON & THE 8 EMOTIONAL VARIABLES
=============================================================================
This dataset provides emotion scores for words across 91 languages.
It combines two major psychological frameworks to score 8 distinct variables:

1. The Dimensional Approach (VAD) | Scale: 1.0 to 9.0 (5.0 is Neutral)
   - Valence: Polarity/Pleasantness (1 = max negative, 9 = max positive)
   - Arousal: Activation/Excitement (1 = sleepy/sluggish, 9 = excited/frantic)
   - Dominance: Perceived control (1 = submissive/weak, 9 = dominant/powerful)

2. The Discrete Approach (BE5) | Scale: 1.0 to 5.0 (1.0 is Neutral/Absence)
   - Joy
   - Anger
   - Sadness
   - Fear
   - Disgust
   (For BE5, 1 indicates a total absence of the emotion, and 5 indicates
   maximum intensity of the emotion).

Note: Because these scores were generated by a regression-based Neural
Network (via cross-lingual distant supervision), floating-point numbers
might occasionally dip slightly below 1.0 or slightly above the maximums.

=============================================================================
REFERENCES & LINKS
=============================================================================
- Original Paper (ACL 2020): "Learning and Evaluating Emotion Lexicons for 91 Languages"
  Read here: https://aclanthology.org/2020.acl-main.112/
- Original Authors: Sven Buechel, Susanna Rücker, and Udo Hahn (JULIE Lab)
- Original GitHub Repository: https://github.com/JULIELab/MEmoLon
- Parquet Conversion Repository: https://github.com/deframer/memolon-parquet
=============================================================================
"""

import pyarrow.parquet as pq

# Load the Parquet file
file_path = "work/memolon-grouped-de-0.1.0.parquet"
table = pq.read_table(file_path)

# Target word to find
word_to_find = "Kirsche"

# Convert the 'word' column to a list and search for the word (case-insensitive)
lowercase_word_list = [str(word).lower() for word in table.column("word").to_pylist()]
lowercase_word_to_find = word_to_find.lower()

try:
    index = lowercase_word_list.index(lowercase_word_to_find)

    # Fetch all data for that row using the found index
    row_data = {col_name: table.column(col_name)[index].as_py() for col_name in table.column_names}
    print(f"Found '{word_to_find}' (case-insensitive search):")
    for key, value in row_data.items():
        print(f"  {key}: {value}")

except ValueError:
    print(f"The word '{word_to_find}' was not found in the dataset.")
