name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # JOB 1: Test & Lint Python App
  test:
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y git make

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: make sync

      - name: Run Linting
        run: make lint

      - name: Run Formatting Check
        run: make format

      - name: Run Type Checking
        run: make type-check

      - name: Run Tests
        run: make test

  # JOB 2: Release Parquet Files
  release:
    needs: [test] # Depends only on the test job
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' # Only run if a tag is pushed
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # Need to checkout code again for the release job context

      - name: Set up Python and Install Dependencies
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install Dependencies
        run: make sync

      - name: Download MEmoLon zip files
        run: make download

      - name: Generate Parquet Files
        run: |
          VERSION_TAG=${{ github.ref_name }}
          VERSION=${VERSION_TAG#v}
          uv run python convert.py --type grouped --language all --version $VERSION --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          # Specify the files to upload as release assets
          files: 'work/*.parquet' # This will upload all .parquet files in the work directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

